import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

import { HomePageComponent } from '@src/app/home-page/home-page.component';
import { VideoworkoutComponent } from '@src/app/videoworkout/videoworkout.component';
import { NguCarouselModule } from '@ngu/carousel';
//import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import {MatButtonModule} from '@angular/material/button';


// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    HomePageComponent,
    VideoworkoutComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
    BrowserModule,
    NguCarouselModule,
    MatButtonModule
    
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
