import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { HomePageComponent } from '@src/app/home-page/home-page.component';
import { VideoworkoutComponent } from '@src/app/videoworkout/videoworkout.component';
import { NguCarouselModule } from '@ngu/carousel';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import {MatButtonModule} from '@angular/material/button';

@NgModule({
  declarations: [
    AppComponent,
    HomePageComponent,
    VideoworkoutComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NguCarouselModule,
    MatButtonModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }